puts "Hello World!"
print "\n"
puts "......"
puts "              .-'';'-.      "
puts "            ,'   <_,-.`.    "
puts "           /)   ,--,_>\_\   "
puts "          |'   (      \_ |  "
puts "          |_    `-.    / |  "
puts "           \`-.   ;  _(`/   "
puts "            `.(    \/ ,'    "
puts "              `-....-'    -hi "